trigger: none

pool:
  vmImage: ubuntu-latest

parameters:
- name: SubscriptionID
  displayName: Subscription ID
  type: string
- name: settingName
  displayName: Setting Name
  type: string
- name: workspaceId
  displayName: Workspace Id
  type: string
- name: eventHubName
  displayName: EventHubName
  type: string
- name: eventHubAuthorizationRuleId
  displayName: eventHubAuthorizationRuleId
  type: string


jobs:
- job:
  steps:
  - script: echo Hello world!
    displayName: 'Placeholder step'

  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      deploymentScope: 'Subscription'
      azureResourceManagerConnection: 'nx-devops'
      subscriptionId: ${{ parameters.SubscriptionID }}
      location: 'East US 2'
      templateLocation: 'Linked artifact'
      csmFile: 'src/main.bicep'
      deploymentMode: 'Incremental'
      overrideParameters: >
        -settingName ${{ parameters.settingName }}
        -workspaceId ${{ parameters.workspaceId }}
        -eventHubName ${{ parameters.eventHubName }}
        -eventHubAuthorizationRuleId ${{ parameters.eventHubAuthorizationRuleId }}